name: chatboat
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  animated_text_kit: ^4.2.2
  flutter_social_button: ^1.1.4+1
  email_validator: ^2.1.17
  flutter_animate: ^4.5.0
  aligned_dialog: ^0.0.7
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gif/
    - assets/images/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proximanova_light.otf
          weight: 300
        - asset: assets/fonts/proximanova_regular.ttf
          weight: 400
        - asset: assets/fonts/Proxima Nova Medium.otf
          weight: 500
        - asset: assets/fonts/proxima_semibold.ttf
          weight: 600
        - asset: assets/fonts/proxima_nova_bold.ttf
          weight: 700
