// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL5OgVq4Cpu7U3CfwTQRTz5xgtOx-v9oo',
    appId: '1:874085453445:web:091810211c18bf6bd623ec',
    messagingSenderId: '874085453445',
    projectId: 'boat-app-d5438',
    authDomain: 'boat-app-d5438.firebaseapp.com',
    databaseURL: 'https://boat-app-d5438-default-rtdb.firebaseio.com',
    storageBucket: 'boat-app-d5438.appspot.com',
    measurementId: 'G-SZ2TFRCPQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLv-3HtHfk86DpSmZYBAyngEDYiWkupo',
    appId: '1:874085453445:android:83a5da00b7f80d00d623ec',
    messagingSenderId: '874085453445',
    projectId: 'boat-app-d5438',
    databaseURL: 'https://boat-app-d5438-default-rtdb.firebaseio.com',
    storageBucket: 'boat-app-d5438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5sdmG7vYverSEcq4r7EpFR_3G48iWcjg',
    appId: '1:874085453445:ios:d1b2e726b329d286d623ec',
    messagingSenderId: '874085453445',
    projectId: 'boat-app-d5438',
    databaseURL: 'https://boat-app-d5438-default-rtdb.firebaseio.com',
    storageBucket: 'boat-app-d5438.appspot.com',
    iosBundleId: 'com.example.chatboat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5sdmG7vYverSEcq4r7EpFR_3G48iWcjg',
    appId: '1:874085453445:ios:967ef187b63de2fbd623ec',
    messagingSenderId: '874085453445',
    projectId: 'boat-app-d5438',
    databaseURL: 'https://boat-app-d5438-default-rtdb.firebaseio.com',
    storageBucket: 'boat-app-d5438.appspot.com',
    iosBundleId: 'com.example.chatboat.RunnerTests',
  );
}
